// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AircncHome: typeof import('./pages/Home/AircncHome.vue')['default']
    AircncHomeList: typeof import('./pages/Home/components/AircncHomeList.vue')['default']
    AircncHomeTabs: typeof import('./pages/Home/components/AircncHomeTabs.vue')['default']
    AircncLogin: typeof import('./pages/Auth/AircncLogin.vue')['default']
    AircncNotFound: typeof import('./pages/AircncNotFound.vue')['default']
    AircncPagination: typeof import('./components/Pagination/AircncPagination.vue')['default']
    AircncProfile: typeof import('./pages/Profile/AircncProfile.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElFooter: typeof import('element-plus/lib')['ElFooter']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTabPane: typeof import('element-plus/lib')['ElTabPane']
    ElTabs: typeof import('element-plus/lib')['ElTabs']
    IEpPicture: typeof import('~icons/ep/picture')['default']
    MainFooter: typeof import('./layouts/components/Footer/MainFooter.vue')['default']
    MainHeader: typeof import('./layouts/components/Header/MainHeader.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
