// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AircncHome: typeof import('./pages/Home/AircncHome.vue')['default']
    AircncHomeList: typeof import('./pages/Home/AircncHomeList.vue')['default']
    AircncHomeTabs: typeof import('./pages/Home/AircncHomeTabs.vue')['default']
    AircncLogin: typeof import('./pages/Auth/AircncLogin.vue')['default']
    AircncNotFound: typeof import('./pages/NotFound/AircncNotFound.vue')['default']
    AircncPagination: typeof import('./components/Pagination/AircncPagination.vue')['default']
    AircncRoomDetails: typeof import('./pages/RoomDetails/AircncRoomDetails.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCarousel: typeof import('element-plus/lib')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/lib')['ElCarouselItem']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDatePicker: typeof import('element-plus/lib')['ElDatePicker']
    ElFooter: typeof import('element-plus/lib')['ElFooter']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTabPane: typeof import('element-plus/lib')['ElTabPane']
    ElTabs: typeof import('element-plus/lib')['ElTabs']
    ElTag: typeof import('element-plus/lib')['ElTag']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpPicture: typeof import('~icons/ep/picture')['default']
    MainFooter: typeof import('./layouts/components/Footer/MainFooter.vue')['default']
    MainHeader: typeof import('./layouts/components/Header/MainHeader.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
